/*
* generated by Xtext
*/
package com.senacor.mdsd.hh.greeter.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import com.senacor.mdsd.hh.greeter.services.GreeterGrammarAccess;

public class GreeterParser extends AbstractContentAssistParser {
	
	@Inject
	private GreeterGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected com.senacor.mdsd.hh.greeter.ui.contentassist.antlr.internal.InternalGreeterParser createParser() {
		com.senacor.mdsd.hh.greeter.ui.contentassist.antlr.internal.InternalGreeterParser result = new com.senacor.mdsd.hh.greeter.ui.contentassist.antlr.internal.InternalGreeterParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getGreetwordAccess().getAlternatives(), "rule__Greetword__Alternatives");
					put(grammarAccess.getModelAccess().getGroup(), "rule__Model__Group__0");
					put(grammarAccess.getPersonAccess().getGroup(), "rule__Person__Group__0");
					put(grammarAccess.getGreetingAccess().getGroup(), "rule__Greeting__Group__0");
					put(grammarAccess.getModelAccess().getPersonsAssignment_0(), "rule__Model__PersonsAssignment_0");
					put(grammarAccess.getModelAccess().getGreetingsAssignment_1(), "rule__Model__GreetingsAssignment_1");
					put(grammarAccess.getPersonAccess().getNameAssignment_1(), "rule__Person__NameAssignment_1");
					put(grammarAccess.getPersonAccess().getFnAssignment_3(), "rule__Person__FnAssignment_3");
					put(grammarAccess.getPersonAccess().getLnAssignment_5(), "rule__Person__LnAssignment_5");
					put(grammarAccess.getGreetingAccess().getGreetwordAssignment_0(), "rule__Greeting__GreetwordAssignment_0");
					put(grammarAccess.getGreetingAccess().getPersonAssignment_1(), "rule__Greeting__PersonAssignment_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			com.senacor.mdsd.hh.greeter.ui.contentassist.antlr.internal.InternalGreeterParser typedParser = (com.senacor.mdsd.hh.greeter.ui.contentassist.antlr.internal.InternalGreeterParser) parser;
			typedParser.entryRuleModel();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public GreeterGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(GreeterGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
