grammar com.senacor.mdsd.GreeterDsl with org.eclipse.xtext.common.Terminals

generate greeterDsl "http://www.senacor.com/mdsd/GreeterDsl"

Model:
	greetings+=Greeting*;
	
Greeting:
	'Hello' name=ID '!';

/*
grammar com.senacor.mdsd.GreeterDsl with org.eclipse.xtext.common.Terminals

generate greeterDsl "http://www.senacor.com/mdsd/GreeterDsl"

Model: (
	persons += Person*
	greetings += Greeting*);
	
Person:
	'Person'
;	
Greeting:
	'Hello' name=ID '!';

*/ 