/*
 * generated by Xtext
 */
package com.senacor.mdsd.hh.splitgreeter.greeter.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractGreeterValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(com.senacor.mdsd.hh.splitgreeter.greeter.greeter.GreeterPackage.eINSTANCE);
		return result;
	}
}
