/*
 * generated by Xtext
 */
package com.senacor.mdsd.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class GreeterDslUiModule extends com.senacor.mdsd.ui.AbstractGreeterDslUiModule {
	public GreeterDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
