/**
 * generated by Xtext 2.9.0
 */
package unihh.sample2;

import unihh.sample2.MyDslStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class MyDslStandaloneSetup extends MyDslStandaloneSetupGenerated {
  public static void doSetup() {
    MyDslStandaloneSetup _myDslStandaloneSetup = new MyDslStandaloneSetup();
    _myDslStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
