/*
* generated by Xtext
*/
package com.senacor.mdsd;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class GreeterDslUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return com.senacor.mdsd.ui.internal.GreeterDslActivator.getInstance().getInjector("com.senacor.mdsd.GreeterDsl");
	}
	
}
