/*
* generated by Xtext
*/
package com.senacor.mdsd.greeter02.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import com.senacor.mdsd.greeter02.services.GreeterDsl02GrammarAccess;

public class GreeterDsl02Parser extends AbstractContentAssistParser {
	
	@Inject
	private GreeterDsl02GrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected com.senacor.mdsd.greeter02.ui.contentassist.antlr.internal.InternalGreeterDsl02Parser createParser() {
		com.senacor.mdsd.greeter02.ui.contentassist.antlr.internal.InternalGreeterDsl02Parser result = new com.senacor.mdsd.greeter02.ui.contentassist.antlr.internal.InternalGreeterDsl02Parser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getPersonAccess().getGenderAlternatives_5_0(), "rule__Person__GenderAlternatives_5_0");
					put(grammarAccess.getGreetwordAccess().getAlternatives(), "rule__Greetword__Alternatives");
					put(grammarAccess.getModelAccess().getGroup(), "rule__Model__Group__0");
					put(grammarAccess.getPersonAccess().getGroup(), "rule__Person__Group__0");
					put(grammarAccess.getGreetingAccess().getGroup(), "rule__Greeting__Group__0");
					put(grammarAccess.getModelAccess().getPersonsAssignment_2(), "rule__Model__PersonsAssignment_2");
					put(grammarAccess.getModelAccess().getGreetingsAssignment_6(), "rule__Model__GreetingsAssignment_6");
					put(grammarAccess.getPersonAccess().getNameAssignment_0(), "rule__Person__NameAssignment_0");
					put(grammarAccess.getPersonAccess().getFirstnameAssignment_2(), "rule__Person__FirstnameAssignment_2");
					put(grammarAccess.getPersonAccess().getLastnameAssignment_4(), "rule__Person__LastnameAssignment_4");
					put(grammarAccess.getPersonAccess().getGenderAssignment_5(), "rule__Person__GenderAssignment_5");
					put(grammarAccess.getGreetingAccess().getWordAssignment_0(), "rule__Greeting__WordAssignment_0");
					put(grammarAccess.getGreetingAccess().getPersonAssignment_1(), "rule__Greeting__PersonAssignment_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			com.senacor.mdsd.greeter02.ui.contentassist.antlr.internal.InternalGreeterDsl02Parser typedParser = (com.senacor.mdsd.greeter02.ui.contentassist.antlr.internal.InternalGreeterDsl02Parser) parser;
			typedParser.entryRuleModel();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public GreeterDsl02GrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(GreeterDsl02GrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
