/*
* generated by Xtext
*/
package com.senacor.mdsd.greeter02;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class GreeterDsl02UiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return com.senacor.mdsd.greeter02.ui.internal.GreeterDsl02Activator.getInstance().getInjector("com.senacor.mdsd.greeter02.GreeterDsl02");
	}
	
}
