/*
* generated by Xtext
*/
package com.senacor.mdsd.hh.splitgreeter.persons;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class PersonsStandaloneSetup extends PersonsStandaloneSetupGenerated{

	public static void doSetup() {
		new PersonsStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

