/*
* generated by Xtext
*/
package com.senacor.mdsd.greeter.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class GreeterDslOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
