/*
* generated by Xtext
*/
package com.senacor.mdsd.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import com.senacor.mdsd.services.GreeterDslGrammarAccess;

public class GreeterDslParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private GreeterDslGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected com.senacor.mdsd.parser.antlr.internal.InternalGreeterDslParser createParser(XtextTokenStream stream) {
		return new com.senacor.mdsd.parser.antlr.internal.InternalGreeterDslParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public GreeterDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(GreeterDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
