/*
* generated by Xtext
*/
package com.senacor.mdsd.hh.splitgreeter.greeter.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class GreeterAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("com/senacor/mdsd/hh/splitgreeter/greeter/parser/antlr/internal/InternalGreeter.tokens");
	}
}
