/*
* generated by Xtext
*/
package com.senacor.mdsd.greeter03.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class GreeterDsl03AntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("com/senacor/mdsd/greeter03/parser/antlr/internal/InternalGreeterDsl03.tokens");
	}
}
