/*
* generated by Xtext
*/
package com.senacor.mdsd.greeter03.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import com.senacor.mdsd.greeter03.services.GreeterDsl03GrammarAccess;

public class GreeterDsl03Parser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private GreeterDsl03GrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected com.senacor.mdsd.greeter03.parser.antlr.internal.InternalGreeterDsl03Parser createParser(XtextTokenStream stream) {
		return new com.senacor.mdsd.greeter03.parser.antlr.internal.InternalGreeterDsl03Parser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public GreeterDsl03GrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(GreeterDsl03GrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
