/*
 * generated by Xtext
 */
package com.senacor.mdsd.hh.splitgreeter.persons.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import com.senacor.mdsd.hh.splitgreeter.persons.ui.internal.PersonsActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class PersonsExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return PersonsActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return PersonsActivator.getInstance().getInjector(PersonsActivator.COM_SENACOR_MDSD_HH_SPLITGREETER_PERSONS_PERSONS);
	}
	
}
