/*
 * generated by Xtext
 */
package com.senacor.mdsd.greeter02;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class GreeterDsl02RuntimeModule extends com.senacor.mdsd.greeter02.AbstractGreeterDsl02RuntimeModule {

}
