/*
* generated by Xtext
*/
package com.senacor.mdsd.greeter02.ui.labeling;

import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider; 
 
import com.google.inject.Inject;
import com.senacor.mdsd.greeter02.greeterDsl02.Greeting;
import com.senacor.mdsd.greeter02.greeterDsl02.Person;

/**
 * Provides labels for a EObjects.
 * 
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#labelProvider
 */
public class GreeterDsl02LabelProvider extends DefaultEObjectLabelProvider {

	@Inject
	public GreeterDsl02LabelProvider(AdapterFactoryLabelProvider delegate) {
		super(delegate);
	}

	//Labels and icons can be computed like this:
	
	String text(Person p) {
		  return ("w".equalsIgnoreCase(p.getGender())?"Frau ":"Herr ")+p.getLastname();
		}
		 
	String text(Greeting grt) {
		  return "Huhu, "+grt.getPerson().getFirstname();
		}
		 
    String image(Greeting grt) {
      return "winken.gif";
    }
}
