/*
* generated by Xtext
*/
package com.senacor.mdsd.hh.splitgreeter.persons;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class PersonsUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return com.senacor.mdsd.hh.splitgreeter.persons.ui.internal.PersonsActivator.getInstance().getInjector("com.senacor.mdsd.hh.splitgreeter.persons.Persons");
	}
	
}
