/*
 * generated by Xtext 2.9.0
 */
package unihh.sample1.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import unihh.sample1.ui.internal.Sample1Activator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MyDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Sample1Activator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return Sample1Activator.getInstance().getInjector(Sample1Activator.UNIHH_SAMPLE1_MYDSL);
	}
	
}
