/*
 * generated by Xtext
 */
package com.senacor.hh.set.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SetDslUiModule extends com.senacor.hh.set.ui.AbstractSetDslUiModule {
	public SetDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
