/*
* generated by Xtext
*/
package com.senacor.mdsd.greeter03.validation;
 
import java.util.ArrayList;
import java.util.List;

import org.eclipse.emf.ecore.EPackage;

public class AbstractGreeterDsl03JavaValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(com.senacor.mdsd.greeter03.greeterDsl03.GreeterDsl03Package.eINSTANCE);
		return result;
	}

}
