/*
* generated by Xtext
*/
package com.senacor.mdsd.greeter03.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import com.senacor.mdsd.greeter03.services.GreeterDsl03GrammarAccess;

public class GreeterDsl03Parser extends AbstractContentAssistParser {
	
	@Inject
	private GreeterDsl03GrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected com.senacor.mdsd.greeter03.ui.contentassist.antlr.internal.InternalGreeterDsl03Parser createParser() {
		com.senacor.mdsd.greeter03.ui.contentassist.antlr.internal.InternalGreeterDsl03Parser result = new com.senacor.mdsd.greeter03.ui.contentassist.antlr.internal.InternalGreeterDsl03Parser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getGreetingAccess().getAlternatives_0(), "rule__Greeting__Alternatives_0");
					put(grammarAccess.getModelAccess().getGroup(), "rule__Model__Group__0");
					put(grammarAccess.getGreetingAccess().getGroup(), "rule__Greeting__Group__0");
					put(grammarAccess.getModelAccess().getGreetingsAssignment_2(), "rule__Model__GreetingsAssignment_2");
					put(grammarAccess.getGreetingAccess().getNameAssignment_1(), "rule__Greeting__NameAssignment_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			com.senacor.mdsd.greeter03.ui.contentassist.antlr.internal.InternalGreeterDsl03Parser typedParser = (com.senacor.mdsd.greeter03.ui.contentassist.antlr.internal.InternalGreeterDsl03Parser) parser;
			typedParser.entryRuleModel();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public GreeterDsl03GrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(GreeterDsl03GrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
