/*
* generated by Xtext
*/
package com.senacor.mdsd.ui.contentassist;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.ui.editor.contentassist.ContentAssistContext;
import org.eclipse.xtext.ui.editor.contentassist.ICompletionProposalAcceptor;

import com.senacor.mdsd.ui.contentassist.AbstractGreeterDsl01ProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class GreeterDsl01ProposalProvider extends AbstractGreeterDsl01ProposalProvider {
}
