/*
 * generated by Xtext
 */
package com.senacor.mdsd;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class GreeterDsl01RuntimeModule extends com.senacor.mdsd.AbstractGreeterDsl01RuntimeModule {

}
