/*
* generated by Xtext
*/
package com.senacor.mdsd.hh.splitgreeter.persons.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import com.senacor.mdsd.hh.splitgreeter.persons.services.PersonsGrammarAccess;

public class PersonsParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private PersonsGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected com.senacor.mdsd.hh.splitgreeter.persons.parser.antlr.internal.InternalPersonsParser createParser(XtextTokenStream stream) {
		return new com.senacor.mdsd.hh.splitgreeter.persons.parser.antlr.internal.InternalPersonsParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public PersonsGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(PersonsGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
