/*
* generated by Xtext
*/
package com.senacor.mdsd.hh.splitgreeter.persons.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class PersonsAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("com/senacor/mdsd/hh/splitgreeter/persons/parser/antlr/internal/InternalPersons.tokens");
	}
}
