/*
 * generated by Xtext
 */
package com.senacor.hh.person01;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class Person01RuntimeModule extends com.senacor.hh.person01.AbstractPerson01RuntimeModule {

}
