/*
 * generated by Xtext
 */
package com.senacor.hh.service.ui.contentassist

import com.senacor.hh.service.ui.contentassist.AbstractServiceDslProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class ServiceDslProposalProvider extends AbstractServiceDslProposalProvider {
}
