/*
* generated by Xtext
*/
package com.senacor.hh.set;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class SetDslStandaloneSetup extends SetDslStandaloneSetupGenerated{

	public static void doSetup() {
		new SetDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

