/*
 * generated by Xtext
 */
package com.senacor.hh.set.ui.contentassist

import com.senacor.hh.set.ui.contentassist.AbstractSetDslProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class SetDslProposalProvider extends AbstractSetDslProposalProvider {
}
