/*
 * generated by Xtext
 */
package com.senacor.mdsd.greeter02.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class GreeterDsl02UiModule extends com.senacor.mdsd.greeter02.ui.AbstractGreeterDsl02UiModule {
	public GreeterDsl02UiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
