/*
 * generated by Xtext
 */
package com.senacor.hh.person01.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class Person01UiModule extends com.senacor.hh.person01.ui.AbstractPerson01UiModule {
	public Person01UiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
