/**
 * generated by Xtext 2.9.0
 */
package unihh.sample2.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Greeting</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link unihh.sample2.myDsl.Greeting#getWord <em>Word</em>}</li>
 *   <li>{@link unihh.sample2.myDsl.Greeting#getPerson <em>Person</em>}</li>
 * </ul>
 *
 * @see unihh.sample2.myDsl.MyDslPackage#getGreeting()
 * @model
 * @generated
 */
public interface Greeting extends EObject
{
  /**
   * Returns the value of the '<em><b>Word</b></em>' attribute.
   * The literals are from the enumeration {@link unihh.sample2.myDsl.Greetword}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Word</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Word</em>' attribute.
   * @see unihh.sample2.myDsl.Greetword
   * @see #setWord(Greetword)
   * @see unihh.sample2.myDsl.MyDslPackage#getGreeting_Word()
   * @model
   * @generated
   */
  Greetword getWord();

  /**
   * Sets the value of the '{@link unihh.sample2.myDsl.Greeting#getWord <em>Word</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Word</em>' attribute.
   * @see unihh.sample2.myDsl.Greetword
   * @see #getWord()
   * @generated
   */
  void setWord(Greetword value);

  /**
   * Returns the value of the '<em><b>Person</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Person</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Person</em>' reference.
   * @see #setPerson(Person)
   * @see unihh.sample2.myDsl.MyDslPackage#getGreeting_Person()
   * @model
   * @generated
   */
  Person getPerson();

  /**
   * Sets the value of the '{@link unihh.sample2.myDsl.Greeting#getPerson <em>Person</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Person</em>' reference.
   * @see #getPerson()
   * @generated
   */
  void setPerson(Person value);

} // Greeting
