/*
 * generated by Xtext 2.9.0
 */
package unihh.sample1.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class MyDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("unihh/sample1/parser/antlr/internal/InternalMyDsl.tokens");
	}
}
