/*
 * generated by Xtext
 */
package com.senacor.mdsd.hh.splitgreeter.persons.ui.contentassist

import com.senacor.mdsd.hh.splitgreeter.persons.ui.contentassist.AbstractPersonsProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class PersonsProposalProvider extends AbstractPersonsProposalProvider {
}
