/*
 * generated by Xtext 2.9.0
 */
package unihh.sample1.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.junit4.IInjectorProvider;
import unihh.sample1.ui.internal.Sample1Activator;

public class MyDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return Sample1Activator.getInstance().getInjector("unihh.sample1.MyDsl");
	}

}
