<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="greeterDsl01" nsURI="http://www.senacor.com/mdsd/GreeterDsl01"
    nsPrefix="greeterDsl01">
  <eClassifiers xsi:type="ecore:EClass" name="Model">
    <eStructuralFeatures xsi:type="ecore:EReference" name="greetings" upperBound="-1"
        eType="#//Greeting" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Greeting"/>
  <eClassifiers xsi:type="ecore:EClass" name="MyGreetword" eSuperTypes="#//Greeting #//GW"/>
  <eClassifiers xsi:type="ecore:EClass" name="GW" eSuperTypes="#//Greeting">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="adressat" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Foo" eSuperTypes="#//MyGreetword"/>
</ecore:EPackage>
