/*
 * generated by Xtext
 */
package com.senacor.mdsd.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import com.senacor.mdsd.ui.internal.GreeterDsl01Activator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class GreeterDsl01ExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return GreeterDsl01Activator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return GreeterDsl01Activator.getInstance().getInjector(GreeterDsl01Activator.COM_SENACOR_MDSD_GREETERDSL01);
	}
	
}
