/*
* generated by Xtext
*/
package com.senacor.mdsd.hh.splitgreeter.persons.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import com.senacor.mdsd.hh.splitgreeter.persons.services.PersonsGrammarAccess;

public class PersonsParser extends AbstractContentAssistParser {
	
	@Inject
	private PersonsGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected com.senacor.mdsd.hh.splitgreeter.persons.ui.contentassist.antlr.internal.InternalPersonsParser createParser() {
		com.senacor.mdsd.hh.splitgreeter.persons.ui.contentassist.antlr.internal.InternalPersonsParser result = new com.senacor.mdsd.hh.splitgreeter.persons.ui.contentassist.antlr.internal.InternalPersonsParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getPersonAccess().getGroup(), "rule__Person__Group__0");
					put(grammarAccess.getModelAccess().getPersonsAssignment(), "rule__Model__PersonsAssignment");
					put(grammarAccess.getPersonAccess().getNameAssignment_1(), "rule__Person__NameAssignment_1");
					put(grammarAccess.getPersonAccess().getFnAssignment_3(), "rule__Person__FnAssignment_3");
					put(grammarAccess.getPersonAccess().getLnAssignment_5(), "rule__Person__LnAssignment_5");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			com.senacor.mdsd.hh.splitgreeter.persons.ui.contentassist.antlr.internal.InternalPersonsParser typedParser = (com.senacor.mdsd.hh.splitgreeter.persons.ui.contentassist.antlr.internal.InternalPersonsParser) parser;
			typedParser.entryRuleModel();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public PersonsGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(PersonsGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
