/*
 * generated by Xtext
 */
package com.senacor.hh.person01.ui.contentassist

import com.senacor.hh.person01.ui.contentassist.AbstractPerson01ProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class Person01ProposalProvider extends AbstractPerson01ProposalProvider {
}
