/*
* generated by Xtext
*/
package com.senacor.mdsd.hh.editortweaks.greeter.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class GreeterGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class ModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Model");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cPersonsAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cPersonsPersonParserRuleCall_0_0 = (RuleCall)cPersonsAssignment_0.eContents().get(0);
		private final Assignment cGreetingsAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cGreetingsGreetingParserRuleCall_1_0 = (RuleCall)cGreetingsAssignment_1.eContents().get(0);
		
		//Model:
		//	persons+=Person* greetings+=Greeting*;
		public ParserRule getRule() { return rule; }

		//persons+=Person* greetings+=Greeting*
		public Group getGroup() { return cGroup; }

		//persons+=Person*
		public Assignment getPersonsAssignment_0() { return cPersonsAssignment_0; }

		//Person
		public RuleCall getPersonsPersonParserRuleCall_0_0() { return cPersonsPersonParserRuleCall_0_0; }

		//greetings+=Greeting*
		public Assignment getGreetingsAssignment_1() { return cGreetingsAssignment_1; }

		//Greeting
		public RuleCall getGreetingsGreetingParserRuleCall_1_0() { return cGreetingsGreetingParserRuleCall_1_0; }
	}

	public class PersonElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Person");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPersonKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cFirstnameKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cFnAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cFnSTRINGTerminalRuleCall_3_0 = (RuleCall)cFnAssignment_3.eContents().get(0);
		private final Keyword cLastnameKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cLnAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cLnSTRINGTerminalRuleCall_5_0 = (RuleCall)cLnAssignment_5.eContents().get(0);
		private final Keyword cSprichtKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cLangAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cLangLanguageEnumRuleCall_7_0 = (RuleCall)cLangAssignment_7.eContents().get(0);
		
		//Person:
		//	"Person" name=ID "firstname" fn=STRING "lastname" ln=STRING "spricht" lang=Language;
		public ParserRule getRule() { return rule; }

		//"Person" name=ID "firstname" fn=STRING "lastname" ln=STRING "spricht" lang=Language
		public Group getGroup() { return cGroup; }

		//"Person"
		public Keyword getPersonKeyword_0() { return cPersonKeyword_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }

		//"firstname"
		public Keyword getFirstnameKeyword_2() { return cFirstnameKeyword_2; }

		//fn=STRING
		public Assignment getFnAssignment_3() { return cFnAssignment_3; }

		//STRING
		public RuleCall getFnSTRINGTerminalRuleCall_3_0() { return cFnSTRINGTerminalRuleCall_3_0; }

		//"lastname"
		public Keyword getLastnameKeyword_4() { return cLastnameKeyword_4; }

		//ln=STRING
		public Assignment getLnAssignment_5() { return cLnAssignment_5; }

		//STRING
		public RuleCall getLnSTRINGTerminalRuleCall_5_0() { return cLnSTRINGTerminalRuleCall_5_0; }

		//"spricht"
		public Keyword getSprichtKeyword_6() { return cSprichtKeyword_6; }

		//lang=Language
		public Assignment getLangAssignment_7() { return cLangAssignment_7; }

		//Language
		public RuleCall getLangLanguageEnumRuleCall_7_0() { return cLangLanguageEnumRuleCall_7_0; }
	}

	public class GreetingElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Greeting");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Assignment cGreetwordAssignment_0_0 = (Assignment)cGroup_0.eContents().get(0);
		private final RuleCall cGreetwordGreetwordEnumRuleCall_0_0_0 = (RuleCall)cGreetwordAssignment_0_0.eContents().get(0);
		private final Assignment cPersonAssignment_0_1 = (Assignment)cGroup_0.eContents().get(1);
		private final CrossReference cPersonPersonCrossReference_0_1_0 = (CrossReference)cPersonAssignment_0_1.eContents().get(0);
		private final RuleCall cPersonPersonIDTerminalRuleCall_0_1_0_1 = (RuleCall)cPersonPersonCrossReference_0_1_0.eContents().get(1);
		private final Keyword cExclamationMarkKeyword_0_2 = (Keyword)cGroup_0.eContents().get(2);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Keyword cZuKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cPersonAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final CrossReference cPersonPersonCrossReference_1_1_0 = (CrossReference)cPersonAssignment_1_1.eContents().get(0);
		private final RuleCall cPersonPersonIDTerminalRuleCall_1_1_0_1 = (RuleCall)cPersonPersonCrossReference_1_1_0.eContents().get(1);
		private final Keyword cSageKeyword_1_2 = (Keyword)cGroup_1.eContents().get(2);
		private final Keyword cIchKeyword_1_3 = (Keyword)cGroup_1.eContents().get(3);
		private final Assignment cGreetwordAssignment_1_4 = (Assignment)cGroup_1.eContents().get(4);
		private final RuleCall cGreetwordGreetwordEnumRuleCall_1_4_0 = (RuleCall)cGreetwordAssignment_1_4.eContents().get(0);
		
		//Greeting:
		//	greetword=Greetword person=[Person] "!" | "Zu" person=[Person] "sage" "ich" greetword=Greetword;
		public ParserRule getRule() { return rule; }

		//greetword=Greetword person=[Person] "!" | "Zu" person=[Person] "sage" "ich" greetword=Greetword
		public Alternatives getAlternatives() { return cAlternatives; }

		//greetword=Greetword person=[Person] "!"
		public Group getGroup_0() { return cGroup_0; }

		//greetword=Greetword
		public Assignment getGreetwordAssignment_0_0() { return cGreetwordAssignment_0_0; }

		//Greetword
		public RuleCall getGreetwordGreetwordEnumRuleCall_0_0_0() { return cGreetwordGreetwordEnumRuleCall_0_0_0; }

		//person=[Person]
		public Assignment getPersonAssignment_0_1() { return cPersonAssignment_0_1; }

		//[Person]
		public CrossReference getPersonPersonCrossReference_0_1_0() { return cPersonPersonCrossReference_0_1_0; }

		//ID
		public RuleCall getPersonPersonIDTerminalRuleCall_0_1_0_1() { return cPersonPersonIDTerminalRuleCall_0_1_0_1; }

		//"!"
		public Keyword getExclamationMarkKeyword_0_2() { return cExclamationMarkKeyword_0_2; }

		//"Zu" person=[Person] "sage" "ich" greetword=Greetword
		public Group getGroup_1() { return cGroup_1; }

		//"Zu"
		public Keyword getZuKeyword_1_0() { return cZuKeyword_1_0; }

		//person=[Person]
		public Assignment getPersonAssignment_1_1() { return cPersonAssignment_1_1; }

		//[Person]
		public CrossReference getPersonPersonCrossReference_1_1_0() { return cPersonPersonCrossReference_1_1_0; }

		//ID
		public RuleCall getPersonPersonIDTerminalRuleCall_1_1_0_1() { return cPersonPersonIDTerminalRuleCall_1_1_0_1; }

		//"sage"
		public Keyword getSageKeyword_1_2() { return cSageKeyword_1_2; }

		//"ich"
		public Keyword getIchKeyword_1_3() { return cIchKeyword_1_3; }

		//greetword=Greetword
		public Assignment getGreetwordAssignment_1_4() { return cGreetwordAssignment_1_4; }

		//Greetword
		public RuleCall getGreetwordGreetwordEnumRuleCall_1_4_0() { return cGreetwordGreetwordEnumRuleCall_1_4_0; }
	}
	
	
	public class GreetwordElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "Greetword");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cDEEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cDEHalloKeyword_0_0 = (Keyword)cDEEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cDEEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cDEHuhuKeyword_1_0 = (Keyword)cDEEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cENEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cENHelloKeyword_2_0 = (Keyword)cENEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cFREnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cFRBonjourKeyword_3_0 = (Keyword)cFREnumLiteralDeclaration_3.eContents().get(0);
		
		//enum Greetword:
		//	DE="Hallo" | DE="Huhu" | EN="Hello" | FR="Bonjour";
		public EnumRule getRule() { return rule; }

		//DE="Hallo" | DE="Huhu" | EN="Hello" | FR="Bonjour"
		public Alternatives getAlternatives() { return cAlternatives; }

		//DE="Hallo"
		public EnumLiteralDeclaration getDEEnumLiteralDeclaration_0() { return cDEEnumLiteralDeclaration_0; }

		//"Hallo"
		public Keyword getDEHalloKeyword_0_0() { return cDEHalloKeyword_0_0; }

		//DE="Huhu"
		public EnumLiteralDeclaration getDEEnumLiteralDeclaration_1() { return cDEEnumLiteralDeclaration_1; }

		//"Huhu"
		public Keyword getDEHuhuKeyword_1_0() { return cDEHuhuKeyword_1_0; }

		//EN="Hello"
		public EnumLiteralDeclaration getENEnumLiteralDeclaration_2() { return cENEnumLiteralDeclaration_2; }

		//"Hello"
		public Keyword getENHelloKeyword_2_0() { return cENHelloKeyword_2_0; }

		//FR="Bonjour"
		public EnumLiteralDeclaration getFREnumLiteralDeclaration_3() { return cFREnumLiteralDeclaration_3; }

		//"Bonjour"
		public Keyword getFRBonjourKeyword_3_0() { return cFRBonjourKeyword_3_0; }
	}

	public class LanguageElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "Language");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cDEEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cDEDeutschKeyword_0_0 = (Keyword)cDEEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cENEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cENEnglischKeyword_1_0 = (Keyword)cENEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cFREnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cFRFranzösischKeyword_2_0 = (Keyword)cFREnumLiteralDeclaration_2.eContents().get(0);
		
		//enum Language:
		//	DE="deutsch" | EN="englisch" | FR="französisch";
		public EnumRule getRule() { return rule; }

		//DE="deutsch" | EN="englisch" | FR="französisch"
		public Alternatives getAlternatives() { return cAlternatives; }

		//DE="deutsch"
		public EnumLiteralDeclaration getDEEnumLiteralDeclaration_0() { return cDEEnumLiteralDeclaration_0; }

		//"deutsch"
		public Keyword getDEDeutschKeyword_0_0() { return cDEDeutschKeyword_0_0; }

		//EN="englisch"
		public EnumLiteralDeclaration getENEnumLiteralDeclaration_1() { return cENEnumLiteralDeclaration_1; }

		//"englisch"
		public Keyword getENEnglischKeyword_1_0() { return cENEnglischKeyword_1_0; }

		//FR="französisch"
		public EnumLiteralDeclaration getFREnumLiteralDeclaration_2() { return cFREnumLiteralDeclaration_2; }

		//"französisch"
		public Keyword getFRFranzösischKeyword_2_0() { return cFRFranzösischKeyword_2_0; }
	}
	
	private ModelElements pModel;
	private PersonElements pPerson;
	private GreetingElements pGreeting;
	private GreetwordElements unknownRuleGreetword;
	private LanguageElements unknownRuleLanguage;
	
	private final Grammar grammar;

	private TerminalsGrammarAccess gaTerminals;

	@Inject
	public GreeterGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("com.senacor.mdsd.hh.editortweaks.greeter.Greeter".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	
	public Grammar getGrammar() {
		return grammar;
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Model:
	//	persons+=Person* greetings+=Greeting*;
	public ModelElements getModelAccess() {
		return (pModel != null) ? pModel : (pModel = new ModelElements());
	}
	
	public ParserRule getModelRule() {
		return getModelAccess().getRule();
	}

	//Person:
	//	"Person" name=ID "firstname" fn=STRING "lastname" ln=STRING "spricht" lang=Language;
	public PersonElements getPersonAccess() {
		return (pPerson != null) ? pPerson : (pPerson = new PersonElements());
	}
	
	public ParserRule getPersonRule() {
		return getPersonAccess().getRule();
	}

	//Greeting:
	//	greetword=Greetword person=[Person] "!" | "Zu" person=[Person] "sage" "ich" greetword=Greetword;
	public GreetingElements getGreetingAccess() {
		return (pGreeting != null) ? pGreeting : (pGreeting = new GreetingElements());
	}
	
	public ParserRule getGreetingRule() {
		return getGreetingAccess().getRule();
	}

	//enum Greetword:
	//	DE="Hallo" | DE="Huhu" | EN="Hello" | FR="Bonjour";
	public GreetwordElements getGreetwordAccess() {
		return (unknownRuleGreetword != null) ? unknownRuleGreetword : (unknownRuleGreetword = new GreetwordElements());
	}
	
	public EnumRule getGreetwordRule() {
		return getGreetwordAccess().getRule();
	}

	//enum Language:
	//	DE="deutsch" | EN="englisch" | FR="französisch";
	public LanguageElements getLanguageAccess() {
		return (unknownRuleLanguage != null) ? unknownRuleLanguage : (unknownRuleLanguage = new LanguageElements());
	}
	
	public EnumRule getLanguageRule() {
		return getLanguageAccess().getRule();
	}

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	} 

	//terminal STRING:
	//	"\"" ("\\" ("b" | "t" | "n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\""))* "\"" | "\'" ("\\" ("b" | "t" |
	//	"n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
