grammar com.senacor.mdsd.greeter02.GreeterDsl02 with org.eclipse.xtext.common.Terminals

generate greeterDsl02 "http://www.senacor.com/mdsd/greeter02/GreeterDsl02"

Model:
	'Persons' '{'
	   persons+=Person*
	'}'
	
	'Greetings' '{'
	   greetings+=Greeting*
	'}';
	
Person:
	name=ID 'firstname' firstname=ID 'lastname' lastname=ID gender=('w'|'m');

Greeting:
	word=Greetword person=[Person] '!';
	
enum Greetword:
  DE='Hallo' | EN='Hello' | FR='Bonjour';
