/*
 * generated by Xtext
 */
package com.senacor.hh.service.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ServiceDslUiModule extends com.senacor.hh.service.ui.AbstractServiceDslUiModule {
	public ServiceDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
