/**
 * generated by Xtext 2.9.0
 */
package unihh.sample1.scoping;

import unihh.sample1.scoping.AbstractMyDslScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class MyDslScopeProvider extends AbstractMyDslScopeProvider {
}
