/*
 * generated by Xtext
 */
package com.senacor.hh.greeter02.generator

import org.eclipse.emf.ecore.resource.Resource
import org.eclipse.xtext.generator.IGenerator
import org.eclipse.xtext.generator.IFileSystemAccess
import com.senacor.hh.greeter02.greeterDsl02.Greeting

/**
 * Generates code from your model files on save.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#TutorialCodeGeneration
 */
class GreeterDsl02Generator implements IGenerator {
	
	override void doGenerate(Resource resource, IFileSystemAccess fsa) {
		System.out.println("starting to generate ...")
		
		fsa.generateFile("abc.txt", "Hallo, Welt")
		
		for (greeting : resource.allContents.toIterable.filter(Greeting)) {
			fsa.generateFile(greeting.name+".txt", "Hallo "+greeting.name)
		}
		
		
//		fsa.generateFile('greetings.txt', 'People to greet: ' + 
//			resource.allContents
//				.filter(typeof(Greeting))
//				.map[name]
//				.join(', '))
	}
}
