/*
 * generated by Xtext
 */
package com.senacor.hh.greeter02.ui.contentassist

import com.senacor.hh.greeter02.ui.contentassist.AbstractGreeterDsl02ProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class GreeterDsl02ProposalProvider extends AbstractGreeterDsl02ProposalProvider {
}
