/*
 * generated by Xtext
 */
package com.senacor.hh.greeter01.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class GreeterUiModule extends com.senacor.hh.greeter01.ui.AbstractGreeterUiModule {
	public GreeterUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
