/*
* generated by Xtext
*/
package com.senacor.mdsd.greeter03.ui.contentassist;

import com.senacor.mdsd.greeter03.ui.contentassist.AbstractGreeterDsl03ProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class GreeterDsl03ProposalProvider extends AbstractGreeterDsl03ProposalProvider {

}
