/**
 * generated by Xtext 2.9.0
 */
package unihh.sample1.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * Customization of the default outline structure.
 * 
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#outline
 */
@SuppressWarnings("all")
public class MyDslOutlineTreeProvider extends DefaultOutlineTreeProvider {
}
