/*
 * generated by Xtext
 */
package com.senacor.mdsd.hh.splitgreeter.persons.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class PersonsUiModule extends com.senacor.mdsd.hh.splitgreeter.persons.ui.AbstractPersonsUiModule {
	public PersonsUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
