/*
 * generated by Xtext 2.9.0
 */
package unihh.sample2.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractMyDslValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(unihh.sample2.myDsl.MyDslPackage.eINSTANCE);
		return result;
	}
	
}
