/*
* generated by Xtext
*/
package com.senacor.mdsd.greeter02.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import com.senacor.mdsd.greeter02.services.GreeterDsl02GrammarAccess;

public class GreeterDsl02Parser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private GreeterDsl02GrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected com.senacor.mdsd.greeter02.parser.antlr.internal.InternalGreeterDsl02Parser createParser(XtextTokenStream stream) {
		return new com.senacor.mdsd.greeter02.parser.antlr.internal.InternalGreeterDsl02Parser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public GreeterDsl02GrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(GreeterDsl02GrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
