grammar com.senacor.mdsd.hh.splitgreeter.greeter.Greeter with org.eclipse.xtext.common.Terminals

import "http://www.senacor.com/mdsd/hh/splitgreeter/persons/Persons" as Persons

generate greeter "http://www.senacor.com/mdsd/hh/splitgreeter/greeter/Greeter"

Model:
	greetings+=Greeting*
;

Greeting:
	greetword=Greetword person=[Persons::Person] '!'
;

enum Greetword:
  DE='Hallo' | DE='Huhu' | EN='Hello' | FR='Bonjour'
;