/**
 * generated by Xtext 2.9.0
 */
package unihh.sample1.myDsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>foo</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link unihh.sample1.myDsl.foo#getDomains <em>Domains</em>}</li>
 *   <li>{@link unihh.sample1.myDsl.foo#getContexts <em>Contexts</em>}</li>
 *   <li>{@link unihh.sample1.myDsl.foo#getAggregates <em>Aggregates</em>}</li>
 * </ul>
 *
 * @see unihh.sample1.myDsl.MyDslPackage#getfoo()
 * @model
 * @generated
 */
public interface foo extends Model
{
  /**
   * Returns the value of the '<em><b>Domains</b></em>' containment reference list.
   * The list contents are of type {@link unihh.sample1.myDsl.Domain}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Domains</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Domains</em>' containment reference list.
   * @see unihh.sample1.myDsl.MyDslPackage#getfoo_Domains()
   * @model containment="true"
   * @generated
   */
  EList<Domain> getDomains();

  /**
   * Returns the value of the '<em><b>Contexts</b></em>' containment reference list.
   * The list contents are of type {@link unihh.sample1.myDsl.Context}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Contexts</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Contexts</em>' containment reference list.
   * @see unihh.sample1.myDsl.MyDslPackage#getfoo_Contexts()
   * @model containment="true"
   * @generated
   */
  EList<Context> getContexts();

  /**
   * Returns the value of the '<em><b>Aggregates</b></em>' containment reference list.
   * The list contents are of type {@link unihh.sample1.myDsl.Aggregate}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Aggregates</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Aggregates</em>' containment reference list.
   * @see unihh.sample1.myDsl.MyDslPackage#getfoo_Aggregates()
   * @model containment="true"
   * @generated
   */
  EList<Aggregate> getAggregates();

} // foo
