/*
 * generated by Xtext
 */
package com.senacor.mdsd.hh.splitgreeter.greeter.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import com.senacor.mdsd.hh.splitgreeter.greeter.ui.internal.GreeterActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class GreeterExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return GreeterActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return GreeterActivator.getInstance().getInjector(GreeterActivator.COM_SENACOR_MDSD_HH_SPLITGREETER_GREETER_GREETER);
	}
	
}
