/*
 * generated by Xtext
 */
package com.senacor.mdsd.greeter03.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import com.senacor.mdsd.greeter03.ui.internal.GreeterDsl03Activator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class GreeterDsl03ExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return GreeterDsl03Activator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return GreeterDsl03Activator.getInstance().getInjector(GreeterDsl03Activator.COM_SENACOR_MDSD_GREETER03_GREETERDSL03);
	}
	
}
