/*
 * generated by Xtext
 */
package com.senacor.mdsd.greeter03;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class GreeterDsl03RuntimeModule extends com.senacor.mdsd.greeter03.AbstractGreeterDsl03RuntimeModule {

}
