/*
* generated by Xtext
*/
package com.senacor.mdsd.greeter03;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class GreeterDsl03StandaloneSetup extends GreeterDsl03StandaloneSetupGenerated{

	public static void doSetup() {
		new GreeterDsl03StandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

