/*
 * generated by Xtext
 */
package com.senacor.mdsd.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class GreeterDsl01UiModule extends com.senacor.mdsd.ui.AbstractGreeterDsl01UiModule {
	public GreeterDsl01UiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
