/*
 * generated by Xtext
 */
package com.senacor.hh.greeter01.ui.contentassist

import com.senacor.hh.greeter01.ui.contentassist.AbstractGreeterProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class GreeterProposalProvider extends AbstractGreeterProposalProvider {
}
