/*
 * generated by Xtext
 */
package com.senacor.hh.greeter01;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class GreeterRuntimeModule extends com.senacor.hh.greeter01.AbstractGreeterRuntimeModule {

}
