/*
* generated by Xtext
*/
package com.senacor.hh.greeter01;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class GreeterStandaloneSetup extends GreeterStandaloneSetupGenerated{

	public static void doSetup() {
		new GreeterStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

