/*
 * generated by Xtext
 */
package com.senacor.mdsd.hh.splitgreeter.greeter.ui.contentassist

import com.senacor.mdsd.hh.splitgreeter.greeter.ui.contentassist.AbstractGreeterProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class GreeterProposalProvider extends AbstractGreeterProposalProvider {
}
