/*
 * generated by Xtext
 */
package com.senacor.mdsd.greeter;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class GreeterDslRuntimeModule extends com.senacor.mdsd.greeter.AbstractGreeterDslRuntimeModule {

}
