/*
 * generated by Xtext
 */
package com.senacor.mdsd.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import com.senacor.mdsd.ui.internal.GreeterDslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class GreeterDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return GreeterDslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return GreeterDslActivator.getInstance().getInjector(GreeterDslActivator.COM_SENACOR_MDSD_GREETERDSL);
	}
	
}
