/*
* generated by Xtext
*/
package com.senacor.mdsd.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import com.senacor.mdsd.services.GreeterDsl01GrammarAccess;

public class GreeterDsl01Parser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private GreeterDsl01GrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected com.senacor.mdsd.parser.antlr.internal.InternalGreeterDsl01Parser createParser(XtextTokenStream stream) {
		return new com.senacor.mdsd.parser.antlr.internal.InternalGreeterDsl01Parser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public GreeterDsl01GrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(GreeterDsl01GrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
