/*
 * generated by Xtext
 */
package com.senacor.mdsd.hh.generator.greeter;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class GreeterRuntimeModule extends com.senacor.mdsd.hh.generator.greeter.AbstractGreeterRuntimeModule {

}
