/*
* generated by Xtext
*/
package com.senacor.mdsd.hh.generator.greeter;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class GreeterStandaloneSetup extends GreeterStandaloneSetupGenerated{

	public static void doSetup() {
		new GreeterStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

