/*
* generated by Xtext
*/
package com.senacor.mdsd.greeter03;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class GreeterDsl03UiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return com.senacor.mdsd.greeter03.ui.internal.GreeterDsl03Activator.getInstance().getInjector("com.senacor.mdsd.greeter03.GreeterDsl03");
	}
	
}
