/*
* generated by Xtext
*/
package com.senacor.mdsd.hh.splitgreeter.greeter;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class GreeterUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return com.senacor.mdsd.hh.splitgreeter.greeter.ui.internal.GreeterActivator.getInstance().getInjector("com.senacor.mdsd.hh.splitgreeter.greeter.Greeter");
	}
	
}
