/*
* generated by Xtext
*/
package com.senacor.mdsd.greeter03.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class GreeterDsl03OutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
