/*
 * generated by Xtext 2.9.0
 */
package unihh.sample2.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.junit4.IInjectorProvider;
import unihh.sample2.ui.internal.Sample2Activator;

public class MyDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return Sample2Activator.getInstance().getInjector("unihh.sample2.MyDsl");
	}

}
