/*
* generated by Xtext
*/
package com.senacor.mdsd.greeter.ui.contentassist;

import com.senacor.mdsd.greeter.ui.contentassist.AbstractGreeterDslProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class GreeterDslProposalProvider extends AbstractGreeterDslProposalProvider {

}
