/*
* generated by Xtext
*/
package com.senacor.mdsd.greeter02.ui.contentassist;

import com.senacor.mdsd.greeter02.ui.contentassist.AbstractGreeterDsl02ProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class GreeterDsl02ProposalProvider extends AbstractGreeterDsl02ProposalProvider {

}
