/*
 * generated by Xtext
 */
package com.senacor.mdsd.hh.splitgreeter.persons.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractPersonsValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(com.senacor.mdsd.hh.splitgreeter.persons.persons.PersonsPackage.eINSTANCE);
		return result;
	}
}
