/*
 * generated by Xtext
 */
package com.senacor.mdsd.greeter03.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class GreeterDsl03UiModule extends com.senacor.mdsd.greeter03.ui.AbstractGreeterDsl03UiModule {
	public GreeterDsl03UiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
