/*
* generated by Xtext
*/
package com.senacor.hh.service;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class ServiceDslStandaloneSetup extends ServiceDslStandaloneSetupGenerated{

	public static void doSetup() {
		new ServiceDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

