/*
 * generated by Xtext
 */
package com.senacor.hh.service;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ServiceDslRuntimeModule extends com.senacor.hh.service.AbstractServiceDslRuntimeModule {

}
